# -*- coding: utf-8 -*-
"""CROO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aHIT_A2qpW_DBNalvaNN_5WqUdSIGsL5
"""

!pip install croo-sdk groq requests nest_asyncio -q
print("✅ Done")

import os
import asyncio
import nest_asyncio
nest_asyncio.apply()  # lets asyncio.run() work inside Jupyter/Kaggle cells

os.environ['CROO_API_URL'] = 'https://api.croo.network'
os.environ['CROO_WS_URL']  = 'wss://api.croo.network/ws'
os.environ['CROO_SDK_KEY'] = ''   # <-- use your ROTATED key here

GROQ_API_KEYS = [
    os.environ.get('GROQ_KEY_1'),
    os.environ.get('GROQ_KEY_2'),
    os.environ.get('GROQ_KEY_3'),
    os.environ.get('GROQ_KEY_4'),
]
PRIMARY_MODEL   = 'llama-3.3-70b-versatile'
SECONDARY_MODEL = 'mixtral-8x7b-32768'

from croo import AgentClient, Config, ListOptions

croo_config = Config(
    base_url=os.environ['CROO_API_URL'],
    ws_url=os.environ['CROO_WS_URL'],
)
croo_client = AgentClient(croo_config, os.environ['CROO_SDK_KEY'])

print("✅ Keys loaded")
print(f"   Primary model   : {PRIMARY_MODEL}")
print(f"   Secondary model : {SECONDARY_MODEL}")
print(f"   Groq keys       : {len(GROQ_API_KEYS)} loaded")

async def test_croo_connection(role="requester"):
    print("🔍 Testing CROO connection...")
    try:
        result = await croo_client.list_negotiations(ListOptions(role=role, page=1, page_size=1))
        print(f"✅ Connected — SDK key is valid. Sample: {result}")
        return True
    except Exception as e:
        print(f"❌ Connection failed: {e}")
        return False

CROO_CONNECTED = asyncio.run(test_croo_connection(role="requester"))

# Strip any stray whitespace/newline from the copied key
os.environ['CROO_SDK_KEY'] = os.environ['CROO_SDK_KEY'].strip()

# Verify it's clean now
key = os.environ['CROO_SDK_KEY']
print(f"Key prefix: {key[:12]}...")
print(f"Key length: {len(key)}")
print(f"Has whitespace/newline: {key != key.strip()}")

# Rebuild the client with the cleaned key
croo_config = Config(
    base_url=os.environ['CROO_API_URL'],
    ws_url=os.environ['CROO_WS_URL'],
)
croo_client = AgentClient(croo_config, key)

# Re-test
CROO_CONNECTED = asyncio.run(test_croo_connection())

key = os.environ['CROO_SDK_KEY']
print(f"Key prefix: {key[:12]}...")
print(f"Key length: {len(key)}")
print(f"Has whitespace/newline: {key != key.strip()}")

from groq import Groq
import time

class RotatingGroqClient:
    def __init__(self, keys):
        self.keys = keys
        self.idx = 0
        self.client = Groq(api_key=keys[0])
        print(f"🔑 Groq ready — {len(keys)} keys loaded")

    def _rotate(self):
        self.idx = (self.idx + 1) % len(self.keys)
        self.client = Groq(api_key=self.keys[self.idx])
        print(f"🔄 Rotated to key #{self.idx + 1}")

    def chat(self, messages, model=None, temperature=0.3, max_tokens=2000):
        if model is None:
            model = PRIMARY_MODEL
        for attempt in range(len(self.keys)):
            try:
                resp = self.client.chat.completions.create(
                    model=model,
                    messages=messages,
                    temperature=temperature,
                    max_tokens=max_tokens
                )
                return resp.choices[0].message.content
            except Exception as e:
                print(f"⚠️ Key #{self.idx+1} error: {e}")
                self._rotate()
                time.sleep(1)
        raise Exception("❌ All Groq keys exhausted")

llm = RotatingGroqClient(GROQ_API_KEYS)

# Test it immediately
test_response = llm.chat([{"role": "user", "content": "Reply with exactly: LLM OK"}])
print(f"✅ LLM test: {test_response}")

import json

def discover_agents():
    print("🔍 Fetching agents from CROO Store...")
    try:
        result = asyncio.run(croo_client.list_services())
        agents = result if isinstance(result, list) else result.get('data', [])

        if agents:
            print(f"✅ Found {len(agents)} real agents on store")
            return agents
        else:
            raise Exception("Empty store")

    except Exception as e:
        print(f"⚠️ Store returned: {e}")
        print("📦 Loading mock agents for testing...")
        return [
            {
                'id': 'mock-audit-001',
                'name': 'Aegis Auditor',
                'price_usdc': 0.01,
                'capability': 'smart_contract_audit',
                'description': 'AI smart contract security auditor',
                'mock': True
            },
            {
                'id': 'mock-intel-002',
                'name': 'Web3 Address Intel',
                'price_usdc': 0.05,
                'capability': 'wallet_intel',
                'description': 'On-chain wallet risk analysis',
                'mock': True
            },
            {
                'id': 'mock-defi-003',
                'name': 'DepegGuard Signal',
                'price_usdc': 0.02,
                'capability': 'defi_risk',
                'description': 'DeFi depeg risk monitor',
                'mock': True
            },
            {
                'id': 'mock-research-004',
                'name': 'Clawintel Research',
                'price_usdc': 0.03,
                'capability': 'blockchain_research',
                'description': 'Blockchain intelligence research',
                'mock': True
            },
        ]

AVAILABLE_AGENTS = discover_agents()

print(f"\n{'='*50}")
print(f"{'Agent':<28} {'Price':<12} {'Type'}")
print(f"{'-'*50}")
for a in AVAILABLE_AGENTS:
    tag = "MOCK" if a.get('mock') else "LIVE"
    print(f"{a['name']:<28} ${a['price_usdc']:<10.4f} [{tag}]")
print(f"{'='*50}")

import requests
import json

CROO_API = os.environ['CROO_API_URL']
CROO_KEY = os.environ['CROO_SDK_KEY']
HEADERS = {
    'Authorization': f'Bearer {CROO_KEY}',
    'Content-Type': 'application/json'
}

def discover_agents():
    print("🔍 Fetching agents from CROO Store via REST...")

    # Try multiple known endpoint patterns
    endpoints = [
        '/v1/services',
        '/v1/agents',
        '/v1/marketplace/agents',
        '/v1/marketplace/services',
        '/api/v1/services',
        '/api/agents',
    ]

    for ep in endpoints:
        try:
            r = requests.get(f'{CROO_API}{ep}', headers=HEADERS, timeout=8)
            print(f"   {ep} → {r.status_code}")
            if r.status_code == 200:
                data = r.json()
                agents = (
                    data if isinstance(data, list)
                    else data.get('data', data.get('services',
                        data.get('agents', [])))
                )
                if agents:
                    print(f"✅ Found {len(agents)} real agents at {ep}")
                    return agents, ep
        except Exception as e:
            print(f"   {ep} → error: {e}")

    print("\n⚠️ No live agents found — using mock agents")
    return None, None

live_agents, working_endpoint = discover_agents()

# Fall back to mock if needed
MOCK_AGENTS = [
    {
        'id': 'mock-audit-001',
        'name': 'Aegis Auditor',
        'price_usdc': 0.01,
        'capability': 'smart_contract_audit',
        'description': 'AI smart contract security auditor',
        'mock': True
    },
    {
        'id': 'mock-intel-002',
        'name': 'Web3 Address Intel',
        'price_usdc': 0.05,
        'capability': 'wallet_intel',
        'description': 'On-chain wallet risk analysis',
        'mock': True
    },
    {
        'id': 'mock-defi-003',
        'name': 'DepegGuard Signal',
        'price_usdc': 0.02,
        'capability': 'defi_risk',
        'description': 'DeFi depeg risk monitor',
        'mock': True
    },
    {
        'id': 'mock-research-004',
        'name': 'Clawintel Research',
        'price_usdc': 0.03,
        'capability': 'blockchain_research',
        'description': 'Blockchain intelligence research',
        'mock': True
    },
]

AVAILABLE_AGENTS = live_agents if live_agents else MOCK_AGENTS
MODE = "LIVE" if live_agents else "MOCK"

print(f"\n{'='*52}")
print(f"Mode: {MODE}")
print(f"{'Agent':<28} {'Price':<12} {'Type'}")
print(f"{'-'*52}")
for a in AVAILABLE_AGENTS:
    tag = "MOCK" if a.get('mock') else "LIVE"
    cap = a.get('capability', a.get('category', 'general'))
    print(f"{a['name']:<28} ${a.get('price_usdc', 0):<10.4f} [{tag}]")
print(f"{'='*52}")
print(f"\n✅ AVAILABLE_AGENTS loaded — {len(AVAILABLE_AGENTS)} agents ready")

def decompose_task(user_task, available_agents):
    agent_list = '\n'.join([
        f"- ID: {a['id']} | Name: {a['name']} | Capability: {a.get('capability','general')} | Price: ${a['price_usdc']} USDC | Description: {a.get('description','')}"
        for a in available_agents
    ])

    prompt = f"""You are NexusAI, an A2A orchestrator on the CROO network.
Your job is to analyze a user task and select the right sub-agents to hire.

AVAILABLE AGENTS:
{agent_list}

USER TASK:
{user_task}

Respond ONLY with valid JSON in this exact format, no extra text:
{{
  "task_summary": "one sentence summary of what needs to be done",
  "execution_plan": [
    {{
      "step": 1,
      "agent_id": "exact agent id from list above",
      "agent_name": "agent name",
      "reason": "why this agent is needed for this task",
      "input": "specific instruction to send this agent",
      "price_usdc": 0.00,
      "can_run_parallel": false
    }}
  ],
  "total_cost_usdc": 0.00,
  "estimated_time": "X minutes"
}}

Rules:
- Only select agents that are genuinely relevant to the task
- Set can_run_parallel to true if the step is independent of others
- total_cost_usdc must be the sum of all step prices
- Return ONLY the JSON object, nothing else"""

    response = llm.chat(
        messages=[{'role': 'user', 'content': prompt}],
        model=PRIMARY_MODEL,
        temperature=0.2
    )

    # Clean and parse
    cleaned = response.strip()
    if '```' in cleaned:
        parts = cleaned.split('```')
        for part in parts:
            if '{' in part:
                cleaned = part.replace('json', '').strip()
                break

    plan = json.loads(cleaned)

    print(f"✅ Task decomposed:")
    print(f"   Summary  : {plan['task_summary']}")
    print(f"   Agents   : {len(plan['execution_plan'])} selected")
    print(f"   Cost     : ${plan['total_cost_usdc']:.4f} USDC")
    print(f"   Est. time: {plan['estimated_time']}")
    return plan

# Test it
test_plan = decompose_task(
    "Check if wallet 0xABC123 is safe and scan for DeFi risks",
    AVAILABLE_AGENTS
)
print(f"\n📋 Full plan:\n{json.dumps(test_plan, indent=2)}")

def show_cost_preview(plan, auto_approve=False):
    print('\n' + '='*54)
    print('🛒  NEXUSAI — COST PREVIEW')
    print('='*54)
    print(f"📋 Task      : {plan['task_summary']}")
    print(f"⏱️  Est. time  : {plan['estimated_time']}")
    print(f"\n{'Step':<6} {'Agent':<26} {'Mode':<14} {'Cost'}")
    print('-'*54)

    for s in plan['execution_plan']:
        mode = '⚡ parallel' if s.get('can_run_parallel') else '🔗 sequential'
        print(f"  {s['step']:<4} {s['agent_name']:<26} {mode:<16} ${s['price_usdc']:.4f}")

    print('-'*54)
    print(f"  {'TOTAL':<46} ${plan['total_cost_usdc']:.4f} USDC")
    print('='*54)

    if auto_approve:
        print("\n✅ Auto-approved")
        return True

    ans = input('\n✅ Approve and run this job? (yes/no): ').strip().lower()
    return ans in ['yes', 'y']

# Test preview
print("\n--- Testing cost preview ---")
approved = show_cost_preview(test_plan, auto_approve=True)
print(f"Approved: {approved}")

def execute_single_order(step):
    agent_id   = step['agent_id']
    agent_name = step['agent_name']
    task_input = step['input']
    price      = step['price_usdc']

    print(f"\n📡 Hiring: {agent_name} (${price} USDC)")

    # ── MOCK MODE ──────────────────────────────────────────
    if agent_id.startswith('mock-'):
        print(f"   [MOCK] Simulating {agent_name}...")
        time.sleep(1.0)

        mock_outputs = {
            'mock-audit-001': {
                'risk_score': 7.2,
                'severity': 'HIGH',
                'findings': [
                    {'severity': 'HIGH',   'issue': 'Reentrancy in withdraw()',        'line': 42},
                    {'severity': 'MEDIUM', 'issue': 'Missing access control on mint()', 'line': 78},
                    {'severity': 'LOW',    'issue': 'Integer overflow risk',            'line': 95},
                ],
                'recommendation': 'Do not deploy without fixing HIGH severity issues',
                'audited_by': 'Aegis AI v2.1'
            },
            'mock-intel-002': {
                'verdict': 'CAUTION',
                'risk_score': 4.5,
                'flags': ['Interacted with Tornado Cash', 'Wallet age < 30 days'],
                'tx_count': 12,
                'volume_usd': 45000,
                'first_seen': '2024-11-02',
                'recommendation': 'Proceed with caution — verify counterparty identity'
            },
            'mock-defi-003': {
                'overall_risk': 'LOW',
                'alerts': [
                    {'token': 'USDC', 'status': 'STABLE', 'deviation': '0.001%'},
                    {'token': 'DAI',  'status': 'STABLE', 'deviation': '0.012%'},
                    {'token': 'USDT', 'status': 'STABLE', 'deviation': '0.003%'},
                ],
                'recommendation': 'No active depeg risk detected'
            },
            'mock-research-004': {
                'summary': 'Protocol shows strong on-chain activity with 98% uptime over 90 days.',
                'data_points': 847,
                'confidence': '94%',
                'sources': ['Etherscan', 'Dune Analytics', 'DefiLlama'],
                'recommendation': 'Protocol appears legitimate and active'
            }
        }

        result = mock_outputs.get(agent_id, {'status': 'completed', 'data': 'mock result'})
        print(f"   ✅ Delivery received from {agent_name}")

        return {
            'agent_id':   agent_id,
            'agent_name': agent_name,
            'status':     'completed',
            'cost_usdc':  price,
            'result':     result,
            'tx_hash':    f'0xMOCK_{agent_id[-3:].upper()}_{int(time.time())}',
            'mock':       True
        }

    # ── REAL CAP ORDER ─────────────────────────────────────
    try:
        print(f"   1/4 Negotiating with {agent_name}...")
        neg = asyncio.run(croo_client.create_negotiation({
            'service_id':      agent_id,
            'requirements':    {'task': task_input},
            'max_price_usdc':  price * 1.1
        }))
        order_id = neg.get('negotiation_id') or neg.get('id')
        print(f"   ✅ Negotiation: {order_id}")

        print(f"   2/4 Paying into escrow...")
        pay = asyncio.run(croo_client.accept_negotiation(order_id))
        tx_hash = pay.get('tx_hash', 'pending')
        print(f"   ✅ TX: {tx_hash}")

        print(f"   3/4 Waiting for delivery...")
        delivery = None
        for i in range(30):
            time.sleep(2)
            status = asyncio.run(croo_client.get_negotiation(order_id))
            state  = status.get('status', status.get('state', ''))
            print(f"       [{i+1}/30] state: {state}")
            if state in ['completed', 'delivered', 'cleared']:
                delivery = status.get('result', status.get('delivery', status))
                break
            if state in ['failed', 'disputed', 'cancelled']:
                raise Exception(f'Order {state}')

        if not delivery:
            raise Exception('Delivery timeout after 60s')

        print(f"   4/4 ✅ Settled on-chain")
        return {
            'agent_id':   agent_id,
            'agent_name': agent_name,
            'status':     'completed',
            'cost_usdc':  price,
            'result':     delivery,
            'tx_hash':    tx_hash,
            'order_id':   order_id,
            'mock':       False
        }

    except Exception as e:
        print(f"   ❌ Failed: {e}")
        return {
            'agent_id':   agent_id,
            'agent_name': agent_name,
            'status':     'failed',
            'error':      str(e),
            'cost_usdc':  0,
            'result':     None
        }

print("✅ Order executor ready")

from concurrent.futures import ThreadPoolExecutor, as_completed

def execute_plan(plan):
    steps      = plan['execution_plan']
    results    = []
    start      = time.time()

    parallel   = [s for s in steps if s.get('can_run_parallel')]
    sequential = [s for s in steps if not s.get('can_run_parallel')]

    if parallel:
        print(f"\n⚡ Running {len(parallel)} steps in parallel...")
        with ThreadPoolExecutor(max_workers=min(len(parallel), 4)) as ex:
            futures = {ex.submit(execute_single_order, s): s for s in parallel}
            for f in as_completed(futures):
                r = f.result()
                results.append(r)
                icon = '✅' if r['status'] == 'completed' else '❌'
                print(f"   {icon} {r['agent_name']} — {r['status']}")

    if sequential:
        print(f"\n🔗 Running {len(sequential)} steps sequentially...")
        for s in sequential:
            r = execute_single_order(s)
            results.append(r)

    elapsed     = round(time.time() - start, 1)
    completed   = [r for r in results if r['status'] == 'completed']
    total_spent = sum(r['cost_usdc'] for r in completed)

    print(f"\n{'='*44}")
    print(f"📊 Execution Summary")
    print(f"{'='*44}")
    print(f"   Completed : {len(completed)}/{len(steps)}")
    print(f"   Spent     : ${total_spent:.4f} USDC")
    print(f"   Time      : {elapsed}s")
    print(f"{'='*44}")

    return results, total_spent

# Test execution
print("--- Testing execution engine ---")
test_results, test_spent = execute_plan(test_plan)

print("\n📦 Raw results from agents:")
for r in test_results:
    print(f"\n{'─'*44}")
    print(f"Agent  : {r['agent_name']}")
    print(f"Status : {r['status']}")
    print(f"Cost   : ${r['cost_usdc']} USDC")
    print(f"TX     : {r['tx_hash']}")
    print(f"Result : {json.dumps(r['result'], indent=4)}")

# Mixtral is decommissioned — replace with current Groq models
PRIMARY_MODEL   = 'llama-3.3-70b-versatile'
SECONDARY_MODEL = 'llama-3.1-8b-instant'  # fast, cheap, still supported

# Recreate client with updated models
llm = RotatingGroqClient(GROQ_API_KEYS)

# Verify both models work
print("Testing PRIMARY model...")
r1 = llm.chat([{"role": "user", "content": "Say: PRIMARY OK"}], model=PRIMARY_MODEL)
print(f"✅ {r1.strip()}")

print("Testing SECONDARY model...")
r2 = llm.chat([{"role": "user", "content": "Say: SECONDARY OK"}], model=SECONDARY_MODEL)
print(f"✅ {r2.strip()}")

print("\n✅ Both models confirmed — now re-run Cell 10 onwards")

def assemble_report(user_task, plan, results, total_spent):
    print("\n🧠 Assembling final report via LLM...")

    results_text = ''
    for r in results:
        results_text += f"\n### {r['agent_name']} (status: {r['status']})\n"
        results_text += json.dumps(r['result'], indent=2) if r['result'] else f"Error: {r.get('error')}"
        results_text += '\n'

    prompt = f"""You are NexusAI, an AI orchestrator. You hired multiple specialist agents
to complete a user task. Combine their outputs into one clear professional report.

USER TASK: {user_task}

AGENT OUTPUTS:
{results_text}

Write a structured report with exactly these sections:

## Executive Summary
2-3 sentences covering the overall finding and verdict.

## Agent Findings

For each agent, one subsection with key data points from their output.

## Risk Assessment
Overall risk level: LOW / MEDIUM / HIGH
Reasoning based on combined agent data.

## Recommendations
Top 3 actionable recommendations numbered 1-3.

## Job Receipt
- Agents hired: list them
- Total cost: ${total_spent:.4f} USDC
- Settled via: CROO CAP on Base

Use the actual numbers and data from agent outputs. Be concise and professional."""

    report = llm.chat(
        messages=[{'role': 'user', 'content': prompt}],
        model=SECONDARY_MODEL,
        temperature=0.4,
        max_tokens=1500
    )

    print("✅ Report assembled")
    return report

test_report = assemble_report(
    "Check if wallet 0xABC123 is safe and scan for DeFi risks",
    test_plan,
    test_results,
    test_spent
)

print("\n" + "="*54)
print("📋 FINAL REPORT")
print("="*54)
print(test_report)

import hashlib

def generate_receipt(user_task, plan, results, total_spent, report):
    receipt = {
        'job_id':          f'NEXUS_{int(time.time())}',
        'timestamp':        time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
        'network':         'Base Mainnet',
        'orchestrator':    'NexusAI v1.0',
        'task_summary':     plan['task_summary'],
        'agents_hired': [
            {
                'name':       r['agent_name'],
                'status':     r['status'],
                'cost_usdc':  r['cost_usdc'],
                'tx_hash':    r.get('tx_hash', 'N/A'),
                'mock':       r.get('mock', False)
            }
            for r in results
        ],
        'total_cost_usdc':  total_spent,
        'report_hash':      hashlib.sha256(report.encode()).hexdigest()
    }

    # Tamper-proof receipt hash
    receipt['receipt_hash'] = hashlib.sha256(
        json.dumps(receipt, sort_keys=True).encode()
    ).hexdigest()

    print('\n' + '='*54)
    print('🧾  NEXUSAI JOB RECEIPT')
    print('='*54)
    print(f"  Job ID     : {receipt['job_id']}")
    print(f"  Timestamp  : {receipt['timestamp']}")
    print(f"  Network    : {receipt['network']}")
    print(f"  Task       : {receipt['task_summary']}")
    print(f"\n  Agents hired:")
    for a in receipt['agents_hired']:
        icon = '✅' if a['status'] == 'completed' else '❌'
        tag  = '[MOCK]' if a['mock'] else '[LIVE]'
        print(f"    {icon} {a['name']:<28} ${a['cost_usdc']:.4f} USDC  {tag}")
        print(f"       TX: {a['tx_hash']}")
    print(f"\n  💵 Total paid : ${receipt['total_cost_usdc']:.4f} USDC")
    print(f"  🔐 Report hash: {receipt['report_hash'][:32]}...")
    print(f"  🔐 Receipt hash: {receipt['receipt_hash'][:32]}...")
    print('='*54)

    return receipt

test_receipt = generate_receipt(
    "Check if wallet 0xABC123 is safe and scan for DeFi risks",
    test_plan,
    test_results,
    test_spent,
    test_report
)

def run_nexusai(user_task, auto_approve=False):
    print('\n' + '='*54)
    print('🤖  NEXUSAI — A2A ORCHESTRATOR')
    print('🏆  CROO Hackathon 2026')
    print('='*54)
    print(f"\n📥 Task received: {user_task}\n")

    # Step 1 — Decompose
    print("🧩 Step 1/5 — Decomposing task with LLM...")
    plan = decompose_task(user_task, AVAILABLE_AGENTS)

    # Step 2 — Cost preview + approval
    print("\n💰 Step 2/5 — Cost preview...")
    approved = show_cost_preview(plan, auto_approve=auto_approve)
    if not approved:
        print("❌ Job cancelled by user.")
        return None

    # Step 3 — Execute via CAP
    print("\n📡 Step 3/5 — Executing via CROO CAP...")
    results, total_spent = execute_plan(plan)

    # Step 4 — Assemble report
    print("\n📊 Step 4/5 — Assembling report...")
    report = assemble_report(user_task, plan, results, total_spent)

    # Step 5 — Generate receipt
    print("\n🧾 Step 5/5 — Generating receipt...")
    receipt = generate_receipt(user_task, plan, results, total_spent, report)

    print('\n' + '='*54)
    print('📋  FINAL REPORT')
    print('='*54)
    print(report)
    print('\n✅ JOB COMPLETE\n')

    return {
        'plan':    plan,
        'results': results,
        'report':  report,
        'receipt': receipt
    }

print("✅ NexusAI orchestrator ready")

output = run_nexusai(
    """
    Audit this smart contract for security vulnerabilities,
    check if wallet 0x742d35Cc6634C0532925a3b8D4C9E5C5 is safe
    to interact with, and alert me of any active DeFi depegging
    risks before I invest.
    """,
    auto_approve=True  # change to False to see the approval prompt
)

import asyncio
import json
import time

async def handle_incoming_job(negotiation):
    """
    Called when another agent or human sends a job to NexusAI via CAP.
    negotiation = the incoming request object from CROO
    """
    neg_id   = negotiation.get('negotiation_id') or negotiation.get('id', 'unknown')
    payload  = negotiation.get('requirements', negotiation.get('input', {}))
    task     = payload.get('task', str(payload))
    budget   = negotiation.get('max_price_usdc', 0.10)

    print(f"\n{'='*54}")
    print(f"📨 INCOMING JOB — {neg_id}")
    print(f"{'='*54}")
    print(f"   Task   : {task}")
    print(f"   Budget : ${budget} USDC")

    # Step 1 — Accept the negotiation (lock in payment)
    try:
        print(f"\n   1/4 Accepting negotiation...")
        accept = await croo_client.accept_negotiation(neg_id)
        print(f"   ✅ Accepted — escrow locked")
    except Exception as e:
        print(f"   ⚠️ Accept failed: {e} — continuing in mock mode")

    # Step 2 — Run full NexusAI pipeline
    print(f"\n   2/4 Running NexusAI pipeline...")
    try:
        plan              = decompose_task(task, AVAILABLE_AGENTS)
        results, spent    = execute_plan(plan)
        report            = assemble_report(task, plan, results, spent)
        receipt           = generate_receipt(task, plan, results, spent, report)
    except Exception as e:
        print(f"   ❌ Pipeline error: {e}")
        report  = f"Error processing task: {e}"
        receipt = {'job_id': f'NEXUS_ERR_{int(time.time())}'}

    # Step 3 — Deliver result back via CAP
    delivery_payload = {
        'report':      report,
        'receipt_id':  receipt.get('job_id'),
        'receipt_hash':receipt.get('receipt_hash', ''),
        'agents_used': [r['agent_name'] for r in results if r['status']=='completed'],
        'total_spent': spent,
        'status':      'completed'
    }

    try:
        print(f"\n   3/4 Delivering result via CAP...")
        await croo_client.deliver_result(neg_id, delivery_payload)
        print(f"   ✅ Result delivered — payment released")
    except Exception as e:
        print(f"   ⚠️ Delivery API not available: {e}")
        print(f"   📦 Result ready (would deliver on live network):")
        print(f"      Report length : {len(report)} chars")
        print(f"      Receipt ID    : {receipt.get('job_id')}")

    print(f"\n   4/4 ✅ Job {neg_id} complete")
    return delivery_payload

print("✅ CAP service handler ready")

async def nexusai_listener(max_polls=5, interval=3):
    """
    Polls CROO for incoming negotiations and handles each one.
    max_polls = how many times to check (set to 999 for production)
    interval  = seconds between polls
    """
    print(f"\n{'='*54}")
    print(f"🎧 NEXUSAI CAP LISTENER — STARTED")
    print(f"{'='*54}")
    print(f"   Polling every {interval}s | Max polls: {max_polls}")
    print(f"   Waiting for incoming jobs...\n")

    seen_ids   = set()
    jobs_done  = 0

    for poll in range(max_polls):
        try:
            # Check for pending negotiations where NexusAI is the provider
            pending = await croo_client.list_negotiations(
                ListOptions(role="provider", page=1, page_size=10)
            )

            new_jobs = [
                n for n in pending
                if (n.get('negotiation_id') or n.get('id')) not in seen_ids
                and n.get('status', '') in ['pending', 'open', 'requested', '']
            ]

            if new_jobs:
                print(f"📬 Poll {poll+1}: {len(new_jobs)} new job(s) found")
                for job in new_jobs:
                    job_id = job.get('negotiation_id') or job.get('id')
                    seen_ids.add(job_id)
                    await handle_incoming_job(job)
                    jobs_done += 1
            else:
                print(f"   Poll {poll+1}/{max_polls} — no new jobs, waiting...")

        except Exception as e:
            print(f"   ⚠️ Poll {poll+1} error: {e}")

        if poll < max_polls - 1:
            await asyncio.sleep(interval)

    print(f"\n{'='*54}")
    print(f"🏁 Listener stopped")
    print(f"   Jobs processed : {jobs_done}")
    print(f"   Polls completed: {max_polls}")
    print(f"{'='*54}")

print("✅ CAP listener ready")

# Inspect what methods the AgentClient actually has
print("📋 All available methods on croo_client:\n")

methods = [m for m in dir(croo_client) if not m.startswith('_')]
for m in methods:
    print(f"  • {m}")

async def handle_incoming_job(negotiation):
    neg_id  = negotiation.get('negotiation_id') or negotiation.get('id', 'unknown')
    payload = negotiation.get('requirements', negotiation.get('input', {}))
    task    = payload.get('task', str(payload))
    budget  = negotiation.get('max_price_usdc', 0.10)

    print(f"\n{'='*54}")
    print(f"📨 INCOMING JOB — {neg_id}")
    print(f"{'='*54}")
    print(f"   Task   : {task}")
    print(f"   Budget : ${budget} USDC")

    # Step 1 — Accept negotiation
    try:
        print(f"\n   1/4 Accepting negotiation...")
        await croo_client.accept_negotiation(neg_id)
        print(f"   ✅ Accepted — escrow locked")
    except Exception as e:
        print(f"   ⚠️ Accept: {e} — continuing")

    # Step 2 — Run full pipeline
    print(f"\n   2/4 Running NexusAI pipeline...")
    try:
        plan           = decompose_task(task, AVAILABLE_AGENTS)
        results, spent = execute_plan(plan)
        report         = assemble_report(task, plan, results, spent)
        receipt        = generate_receipt(task, plan, results, spent, report)
    except Exception as e:
        print(f"   ❌ Pipeline error: {e}")
        report  = f"Error: {e}"
        receipt = {'job_id': f'NEXUS_ERR_{int(time.time())}',
                   'receipt_hash': '', 'report_hash': ''}
        results = []
        spent   = 0.0

    delivery_payload = {
        'report':       report,
        'receipt_id':   receipt.get('job_id'),
        'receipt_hash': receipt.get('receipt_hash', ''),
        'agents_used':  [r['agent_name'] for r in results if r['status']=='completed'],
        'total_spent':  spent,
        'status':       'completed'
    }

    # Step 3 — Deliver result via correct SDK method
    try:
        print(f"\n   3/4 Delivering result via CAP...")
        await croo_client.deliver_order(
            neg_id,
            json.dumps(delivery_payload)   # deliver_order expects a string
        )
        print(f"   ✅ Delivered — payment released to NexusAI wallet")
    except Exception as e:
        print(f"   ⚠️ deliver_order: {e}")
        # Try alternate signature
        try:
            await croo_client.deliver_order(
                order_id=neg_id,
                result=json.dumps(delivery_payload)
            )
            print(f"   ✅ Delivered (kwarg signature)")
        except Exception as e2:
            print(f"   ⚠️ Both signatures failed: {e2}")
            print(f"   📦 Payload ready ({len(report)} chars) — will deliver on live network")

    print(f"\n   4/4 ✅ Job {neg_id} complete")
    return delivery_payload

print("✅ handle_incoming_job patched with deliver_order")

inbound_result = simulate_incoming_job()

import inspect

print("deliver_order signature:")
print(inspect.signature(croo_client.deliver_order))
print()

# Also check what dataclasses the SDK exports
import croo
print("Croo SDK exports:")
exports = [x for x in dir(croo) if not x.startswith('_')]
for e in exports:
    print(f"  • {e}")

from croo import DeliverOrderRequest, DeliverableType

async def handle_incoming_job(negotiation):
    neg_id  = negotiation.get('negotiation_id') or negotiation.get('id', 'unknown')
    payload = negotiation.get('requirements', negotiation.get('input', {}))
    task    = payload.get('task', str(payload))
    budget  = negotiation.get('max_price_usdc', 0.10)

    print(f"\n{'='*54}")
    print(f"📨 INCOMING JOB — {neg_id}")
    print(f"{'='*54}")
    print(f"   Task   : {task}")
    print(f"   Budget : ${budget} USDC")

    # Step 1 — Accept
    try:
        print(f"\n   1/4 Accepting negotiation...")
        await croo_client.accept_negotiation(neg_id)
        print(f"   ✅ Accepted — escrow locked")
    except Exception as e:
        print(f"   ⚠️ Accept: {e} — continuing")

    # Step 2 — Run pipeline
    print(f"\n   2/4 Running NexusAI pipeline...")
    try:
        plan           = decompose_task(task, AVAILABLE_AGENTS)
        results, spent = execute_plan(plan)
        report         = assemble_report(task, plan, results, spent)
        receipt        = generate_receipt(task, plan, results, spent, report)
    except Exception as e:
        print(f"   ❌ Pipeline error: {e}")
        report  = f"Error: {e}"
        receipt = {'job_id': f'NEXUS_ERR_{int(time.time())}',
                   'receipt_hash': '', 'report_hash': ''}
        results = []
        spent   = 0.0

    # Step 3 — Deliver using correct dataclass
    delivery_text = json.dumps({
        'report':       report,
        'receipt_id':   receipt.get('job_id'),
        'receipt_hash': receipt.get('receipt_hash', ''),
        'agents_used':  [r['agent_name'] for r in results if r['status']=='completed'],
        'total_spent':  spent,
        'status':       'completed'
    })

    try:
        print(f"\n   3/4 Delivering result via CAP...")
        await croo_client.deliver_order(
            neg_id,
            DeliverOrderRequest(
                deliverable_type=DeliverableType.TEXT,
                deliverable_text=delivery_text
            )
        )
        print(f"   ✅ Delivered — payment released to NexusAI wallet")
    except Exception as e:
        print(f"   ⚠️ deliver_order: {e}")
        print(f"   📦 Payload ready ({len(report)} chars) — will deliver on live network")

    print(f"\n   4/4 ✅ Job {neg_id} complete")
    return delivery_text

print("✅ handle_incoming_job fully patched")